version: "3"
services:
  # ------------------
  nginx:
    container_name: xw_nginx
    image: nginx:alpine

    ports:
      - "81:8011"
      - "80:8012"
      - "443:443"
    volumes:
      - ./www/:/var/www/
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/

  # ------------------
  php:
    build: ./conf/php/
    container_name: xw_php
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/
      - ./conf/php/etc:/usr/local/etc/

  # ------------------
  redis:
    user: "root"
    container_name: xw_redis
    image: redis
    ports:
      - "4399:6379"
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
      - ./data/redis/:/usr/local/var/db/redis/
    command: redis-server /etc/redis.conf

  # ------------------
  mysql_master:
    user: "mysql"
    container_name: mysql-master
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql/3307/:/var/lib/mysql/:rw
      - ./conf/mysql/3307/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./log/mysql/3307:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456_master"

  # ------------------
  mysql_slave:
    user: "mysql"
    container_name: mysql-slave
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql/3308/:/var/lib/mysql/:rw
      - ./conf/mysql/3308/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./log/mysql/3308/:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456_slave"
