version: "3"
services:
  # ------------------
  nginx:
    container_name: xw_nginx
    image: nginx:alpine

    ports:
      - "80:8012"
      - "443:443"
    volumes:
      - ./www/:/var/www/
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/

  # ------------------
  php:
    build: ./conf/php/
    container_name: xw_php
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/
      - ./conf/php/etc:/usr/local/etc/

  # ------------------
  redis:
    user: "root"
    container_name: xw_redis
    image: redis
    ports:
      - "4399:6379"
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
      - ./data/redis/:/usr/local/var/db/redis/
    command: redis-server /etc/redis.conf

  # ------------------
  mysql_master:
    user: "mysql"
    container_name: mysql-master
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql/:rw
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./log/mysql:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  # ------------------
  fund-stock-timer:
    image: iszmxw/fund-stock-timer:latest
    container_name: xw-timer
    restart: always
    environment:
      CONFIG_FILE: ./config
    volumes:
      - /home/yezhiming/binary/fund-stock/timer:/home/yezhiming/binary/timer/config
      - /home/yezhiming/binary/logs:/home/yezhiming/binary/timer/logs
  # ------------------

  # ------------------
  gotify:
    image: gotify/server
    container_name: xw-gotify
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - GOTIFY_DEFAULTUSER_PASS=123456
    volumes:
      - /home/yezhiming/binary/gotify/data:/app/data
  # ------------------
